### ISSUE TITLE
UI implementation to change the user password.

### ISSUE THREAD

**Issue by Squadella** [ManaZeak/ManaZeak#191]
# Status : 
The user cannot change the password in the UI. It opens an empty modal without any fields.

# Steps : 

- [x] Expand the interaction zone to change the password to the whole button and not only the icon.
- [x] Modify the file `templates/fragments/modal/reset-password.html` to add the fields new password. 
- [x] Call the URL `/resetPassword/` with `POST` method with the following JSON :
    ```json
    {
        "newPassword1": "XXX",
        "newPassword2": "XXX"
    }
    ```

**Comment by ArthurBeaulieu** [comment]
@Squadella , shouldn't we add an existingPassword to the post, so not anyone can update an account password ?

**Comment by Squadella** [comment]
Tested in dev mode, to be tested in production.
