### ISSUE TITLE
Labels in mainpage

### ISSUE THREAD

**Issue by ArthurBeaulieu** [ManaZeak/ManaZeak#240]
On main page, the random selected label items should not include self-released artists (ie label name that do NOT contain " Records").
I think for future "All label view", it should apply same principle to hide self-released "virtual labels"

**Comment by Squadella** [comment]
This needs some adaptation in the database structure of the application.

- [ ] Add a column `artist_released` 
- [ ] Fill the column with false if the label doesn't end by ` Records`
- [ ] In the random label table, filter the label with only the label with `artist_released = false`
- [ ] Add an index on the `artist_released` column to speed the queries on it.
